### ISSUE TITLE
bug: the query section is not available

### ISSUE THREAD

**Issue by yeikel16** [deta/docs#191]
I'm working on a version of your HTTP API in the Dart language, but I can't access the [URL](https://docs.deta.sh/docs/base/http/sdk#queries) because the hyperlink is not available.

Deta seems to me to be a magnificent project with a splendid future. I would like, if possible, to make this version of the dart library available to the community. This is the [repository](https://github.com/yeikel16/deta-dart/).

**Comment by abdelhai** [comment]
hi @yeikel16 sorry for the late response, we might have answered this somewhere else. but in case not, this is the link https://docs.deta.sh/docs/base/queries
