### ISSUE TITLE
uploading the image to deta drive is not working

### ISSUE THREAD

**Issue by rohan2734** [deta/docs#194]
![image](https://user-images.githubusercontent.com/58523134/153985245-9965c94b-ad01-4a9b-b22b-85bc9ad57dfa.png)

![image](https://user-images.githubusercontent.com/58523134/153985299-4691cf72-cf4a-4817-9d30-53b2842c074b.png)

is there any issue in deta?

**Comment by taslater** [comment]
Are you deploying your code to a Deta Micro? I don't believe it will work if you are just running locally.

#181 addresses this documentation issue. @aavshr mentioned this [here](https://github.com/deta/docs/issues/181#issuecomment-988672760). [This](https://docs.deta.sh/docs/micros/getting_started/) should show you how to create and deploy a micro to run the examples in the [docs](https://docs.deta.sh/docs/home/).

**Comment by roshangm1** [comment]
`TypeError: Cannot read properties of undefined (reading 'upload_id')`
This seems to be the real error.
