### ISSUE TITLE
"Bad Gateway" error

### ISSUE THREAD

**Issue by dlink1999** [deta/docs#209]
Hi, ther:

  I am pretty new in fastai and deta.

  I follow the tutorial code, and deploy micro successfully. 

"from fastapi import FastAPI, File, UploadFile 
from fastapi.responses import HTMLResponse, StreamingResponse 
from deta import Deta 
 
app = FastAPI() 
deta = Deta()  # configure your Deta project  
drive = deta.Drive("photos") # access to your drive"

  But it doesn't work, the Visor shows the following message. What do I miss?

"Traceback (most recent call last):
  File "/opt/python/detalib/debugger.py", line 142, in wrap
    result = func(event, context)
  File "/var/task/_entry.py", line 12, in handler
    import main  # noqa
  File "/var/task/main.py", line 7, in <module>
    drive = deta.Drive("photos") # access to your drive
AttributeError: 'Deta' object has no attribute 'Drive'"

**Comment by abdelhai** [comment]
hi, ask questions here: https://github.com/orgs/deta/discussions

**Comment by dlink1999** [comment]
> hi, ask questions here: https://github.com/orgs/deta/discussions

Thanks
