### ISSUE TITLE
Error: failed to update dependencies: Internal server error

### ISSUE THREAD

**Issue by Hrushi11** [deta/docs#266]
My `requirements.txt` file includes `tensorflow` package. Once I take this requirement out the build works properly. Does deta not support tensorflow..

```
Deploying...
Successfully deployed changes
Updating dependencies...
Error: failed to update dependencies: Internal server error
```

Please let me know how I can resolve this or deta has some restrictions in requirements that we can include.

**Comment by abdelhai** [comment]
hi, tf size exceeds our limits and can't run on deta micros yet https://docs.deta.sh/docs/micros/about#important-notes (7-8)

**Comment by Hrushi11** [comment]
> hi, tf size exceeds our limits and can't run on deta micros yet https://docs.deta.sh/docs/micros/about#important-notes (7-8)

Thanks a lot, Got it!
