### ISSUE TITLE
Bad query results in crash

### ISSUE THREAD

**Issue by mslourens** [deta/docs#667]
When I try to query my data using a bad query, the server crashes.

**Steps to reproduce:**
1. Create a nodejs app (see [StackBlitz](https://stackblitz.com/edit/node-17mlub?file=index.js))
2. Try to get the surveys with empty questions using the endpoint `http://localhost:3102/surveys/unanswered`
3. Notice the server crashes with error `Bad query`

Expected behavior: I would expect the server never to crash, but to return a 500 error with the message 'Bad query'.

**Comment by sudo-subg** [comment]
Delete the project key from your [Deta dashboard](https://web.deta.sh/) under `Project Keys` tab. You should not share your project keys publicly.

**Comment by sudo-subg** [comment]
Your query `{ 'questions.answer?': '' }` is not of the right format. There is no operator after `?`. That's what causing your node server to crash.
Again please remove your project key from your Deta dashboard and the StackBlitz environment you have shared.

**Comment by mslourens** [comment]
Sorry, I thought it was just a test project, I could share it, but it will open the project up to everyone with bad intent. I removed the project key. And the issue is all mine, because my express implementation was not catching any errors, therefore it crashed. I will close this issue.
